REALIZADOS CON VALORES DE EJEMPLO

//REQUERIMIENTO DE CONSULTA 1:

--Hay 6 tipos de consultas, 3 para la búsqueda por regiones y 3 para la búsqueda por id del punto
--Hay dos para hallar por fechas y uno para hallar por horas en cada uno

ADMINISTRADOR PLAN Y REGIONALES:
//POR REGION

EN UNA FECHA:
SELECT CITA.DOCUMENTO_CIUDADANO, CIUDADANO.NOMBRE 
FROM (CITA JOIN CIUDADANO ON CITA.DOCUMENTO_CIUDADANO = CIUDADANO.DOCUMENTO)
     JOIN PUNTO ON CITA.ID_PUNTO = PUNTO.ID 
WHERE CITA.FECHAHORA BETWEEN TO_DATE('12-08-2021 00:00', 'DD-MM-YYYY HH24:MI') AND TO_DATE('12-08-2021 23:59', 'DD-MM-YYYY HH24:MI')
      AND PUNTO.REGION = 'TUNJA'
      AND CITA.FINALIZADA = 'T';

RANGO DE FECHAS:

SELECT CITA.DOCUMENTO_CIUDADANO, CIUDADANO.NOMBRE 
FROM (CITA JOIN CIUDADANO ON CITA.DOCUMENTO_CIUDADANO = CIUDADANO.DOCUMENTO)
     JOIN PUNTO ON CITA.ID_PUNTO = PUNTO.ID 
WHERE CITA.FECHAHORA BETWEEN TO_DATE('01-01-2021 00:00', 'DD-MM-YYYY HH24:MI') AND TO_DATE('31-12-2021 23:59', 'DD-MM-YYYY HH24:MI')
      AND PUNTO.REGION = 'ANTIOQUIA'
      AND CITA.FINALIZADA = 'T';

RANGO DE HORAS: 

SELECT CITA.DOCUMENTO_CIUDADANO, CIUDADANO.NOMBRE 
FROM (CITA JOIN CIUDADANO ON CITA.DOCUMENTO_CIUDADANO = CIUDADANO.DOCUMENTO)
     JOIN PUNTO ON CITA.ID_PUNTO = PUNTO.ID 
WHERE (EXTRACT(HOUR FROM CAST(CITA.FECHAHORA AS TIMESTAMP)) BETWEEN 13 AND 16)
      AND EXTRACT(MINUTE FROM CAST(CITA.FECHAHORA AS TIMESTAMP)) BETWEEN 20 AND 30
      AND PUNTO.REGION = 'ANTIOQUIA'
      AND CITA.FINALIZADA = 'T';

ADMINISTRADOR DE UN PUNTO:

EN UNA FECHA:
SELECT CITA.DOCUMENTO_CIUDADANO, CIUDADANO.NOMBRE 
FROM (CITA JOIN CIUDADANO ON CITA.DOCUMENTO_CIUDADANO = CIUDADANO.DOCUMENTO)
     JOIN PUNTO ON CITA.ID_PUNTO = PUNTO.ID 
WHERE CITA.FECHAHORA BETWEEN TO_DATE('12-08-2021 00:00', 'DD-MM-YYYY HH24:MI') AND TO_DATE('12-08-2021 23:59', 'DD-MM-YYYY HH24:MI')
      AND PUNTO.REGION = 'TUNJA'
      AND CITA.FINALIZADA = 'T';

RANGO DE FECHAS:

SELECT CITA.DOCUMENTO_CIUDADANO, CIUDADANO.NOMBRE 
FROM (CITA JOIN CIUDADANO ON CITA.DOCUMENTO_CIUDADANO = CIUDADANO.DOCUMENTO)
     JOIN PUNTO ON CITA.ID_PUNTO = PUNTO.ID 
WHERE CITA.FECHAHORA BETWEEN TO_DATE('01-01-2021 00:00', 'DD-MM-YYYY HH24:MI') AND TO_DATE('31-12-2021 23:59', 'DD-MM-YYYY HH24:MI')
      AND PUNTO.REGION = '20'
      AND CITA.FINALIZADA = 'T';

RANGO DE HORAS: 

SELECT CITA.DOCUMENTO_CIUDADANO, CIUDADANO.NOMBRE 
FROM (CITA JOIN CIUDADANO ON CITA.DOCUMENTO_CIUDADANO = CIUDADANO.DOCUMENTO)
     JOIN PUNTO ON CITA.ID_PUNTO = PUNTO.ID 
WHERE (EXTRACT(HOUR FROM CAST(CITA.FECHAHORA AS TIMESTAMP)) BETWEEN 13 AND 16)
      AND EXTRACT(MINUTE FROM CAST(CITA.FECHAHORA AS TIMESTAMP)) BETWEEN 20 AND 30
      AND PUNTO.REGION = '20'
      AND CITA.FINALIZADA = 'T';

//REQUERIMIENTO DE CONSULTA 2

--Consiste de 2 consultas para cada caso, una crea una tabla con la información necesaria y la otra extrae la información de los id de los puntos
--Hay dos tipos de consultas: para rangos de fechas y para rangos de horas

PARA UNA SOLA FECHA/RANGO DE FECHAS:

CREATE TABLE INFO (ID, DESCRIP, APLIC) AS
(SELECT PUNTO.ID, ESTADO.DESCRIPCION, COUNT(*) AS APLICADAS
FROM ((PUNTO JOIN CITA ON PUNTO.ID = CITA.ID_PUNTO)
     JOIN CIUDADANO ON CIUDADANO.DOCUMENTO = CITA.DOCUMENTO_CIUDADANO)
     JOIN ESTADO ON CIUDADANO.ID_ESTADO = ESTADO.ID
WHERE CITA.FECHAHORA BETWEEN TO_DATE('01-04-2021 00:00', 'DD-MM-YYYY HH24:MI') AND TO_DATE('01-04-2021 23:59', 'DD-MM-YYYY HH24:MI')
GROUP BY ESTADO.DESCRIPCION, PUNTO.ID HAVING ESTADO.DESCRIPCION LIKE '%VACUNA%')
ORDER BY APLICADAS DESC;

SELECT INFO.ID
FROM INFO
FETCH FIRST 20 ROWS ONLY;

PARA UN RANGO DE HORAS:

CREATE TABLE INFO (ID, DESCRIP, APLIC) AS
(SELECT PUNTO.ID, ESTADO.DESCRIPCION, COUNT(*) AS APLICADAS
FROM ((PUNTO JOIN CITA ON PUNTO.ID = CITA.ID_PUNTO)
     JOIN CIUDADANO ON CIUDADANO.DOCUMENTO = CITA.DOCUMENTO_CIUDADANO)
     JOIN ESTADO ON CIUDADANO.ID_ESTADO = ESTADO.ID
WHERE CITA.FECHAHORA BETWEEN TO_DATE('01-04-2021 00:00', 'DD-MM-YYYY HH24:MI') AND TO_DATE('01-05-2021 23:59', 'DD-MM-YYYY HH24:MI')
GROUP BY ESTADO.DESCRIPCION, PUNTO.ID HAVING ESTADO.DESCRIPCION LIKE '%VACUNA%')
ORDER BY APLICADAS DESC;

SELECT INFO.ID
FROM INFO
FETCH FIRST 20 ROWS ONLY;

//REQUERIMIENTO DE CONSULTA 3:

--La consulta fue realizada con valores de ejemplo que muestran el funcionamiento correcto
--Consiste de 3 consultas: una para extraer en una nueva tabla los datos de todo el grupo poblacional;
--una para hallar el índice de acuerdo a los datos de la tabla creada;
--y una para eliminar la tabla creada y dejar la base de datos limpia
CREATE TABLE CANTIDAD AS (
SELECT ES.DESCRIPCION, COUNT(*) AS CANT
FROM CIUDADANO C,EPS E, ESTADO ES, PRIORIZACION P, CITA CI
WHERE E.ID = C.ID_EPS AND
      ES.ID = C.ID_ESTADO AND
      C.DOCUMENTO = P.DOCUMENTO_CIUDADANO AND
      CI.DOCUMENTO_CIUDADANO = C.DOCUMENTO AND
      C.HABILITADO = 'T'
      AND E.ID IN ('12','13','14','15')
GROUP BY ES.DESCRIPCION);

SELECT CANT/ (SELECT SUM(CANT)
             FROM CANTIDAD) AS INDICE
FROM CANTIDAD
WHERE DESCRIPCION LIKE 'VACUNADO%';

DROP TABLE "CANTIDAD";